#pragma checksum "C:\Users\Valadão\source\repos\mvc - teste prático\mvc - teste prático\Views\Produtos\Index.cshtml" "{ff1816ec-aa5e-4d10-87f7-6f4963833460}" "06532c027761429406e6cb1c9a3599e1475dcd44"
// <auto-generated/>
#pragma warning disable 1591
[assembly: global::Microsoft.AspNetCore.Razor.Hosting.RazorCompiledItemAttribute(typeof(AspNetCore.Views_Produtos_Index), @"mvc.1.0.view", @"/Views/Produtos/Index.cshtml")]
namespace AspNetCore
{
    #line hidden
    using System;
    using System.Collections.Generic;
    using System.Linq;
    using System.Threading.Tasks;
    using Microsoft.AspNetCore.Mvc;
    using Microsoft.AspNetCore.Mvc.Rendering;
    using Microsoft.AspNetCore.Mvc.ViewFeatures;
#nullable restore
#line 1 "C:\Users\Valadão\source\repos\mvc - teste prático\mvc - teste prático\Views\_ViewImports.cshtml"
using mvc___teste_prático;

#line default
#line hidden
#nullable disable
#nullable restore
#line 2 "C:\Users\Valadão\source\repos\mvc - teste prático\mvc - teste prático\Views\_ViewImports.cshtml"
using mvc___teste_prático.Models;

#line default
#line hidden
#nullable disable
    [global::Microsoft.AspNetCore.Razor.Hosting.RazorSourceChecksumAttribute(@"SHA1", @"06532c027761429406e6cb1c9a3599e1475dcd44", @"/Views/Produtos/Index.cshtml")]
    [global::Microsoft.AspNetCore.Razor.Hosting.RazorSourceChecksumAttribute(@"SHA1", @"a85e8cc57502d090475a6cafe15e033ccf8588f8", @"/Views/_ViewImports.cshtml")]
    #nullable restore
    public class Views_Produtos_Index : global::Microsoft.AspNetCore.Mvc.Razor.RazorPage<dynamic>
    #nullable disable
    {
        #line hidden
        #pragma warning disable 0649
        private global::Microsoft.AspNetCore.Razor.Runtime.TagHelpers.TagHelperExecutionContext __tagHelperExecutionContext;
        #pragma warning restore 0649
        private global::Microsoft.AspNetCore.Razor.Runtime.TagHelpers.TagHelperRunner __tagHelperRunner = new global::Microsoft.AspNetCore.Razor.Runtime.TagHelpers.TagHelperRunner();
        #pragma warning disable 0169
        private string __tagHelperStringValueBuffer;
        #pragma warning restore 0169
        private global::Microsoft.AspNetCore.Razor.Runtime.TagHelpers.TagHelperScopeManager __backed__tagHelperScopeManager = null;
        private global::Microsoft.AspNetCore.Razor.Runtime.TagHelpers.TagHelperScopeManager __tagHelperScopeManager
        {
            get
            {
                if (__backed__tagHelperScopeManager == null)
                {
                    __backed__tagHelperScopeManager = new global::Microsoft.AspNetCore.Razor.Runtime.TagHelpers.TagHelperScopeManager(StartTagHelperWritingScope, EndTagHelperWritingScope);
                }
                return __backed__tagHelperScopeManager;
            }
        }
        private global::Microsoft.AspNetCore.Mvc.TagHelpers.FormTagHelper __Microsoft_AspNetCore_Mvc_TagHelpers_FormTagHelper;
        private global::Microsoft.AspNetCore.Mvc.TagHelpers.RenderAtEndOfFormTagHelper __Microsoft_AspNetCore_Mvc_TagHelpers_RenderAtEndOfFormTagHelper;
        private global::Microsoft.AspNetCore.Mvc.TagHelpers.OptionTagHelper __Microsoft_AspNetCore_Mvc_TagHelpers_OptionTagHelper;
        #pragma warning disable 1998
        public async override global::System.Threading.Tasks.Task ExecuteAsync()
        {
#nullable restore
#line 1 "C:\Users\Valadão\source\repos\mvc - teste prático\mvc - teste prático\Views\Produtos\Index.cshtml"
  
    ViewData["Title"] = "Cadastro de Produtos";

#line default
#line hidden
#nullable disable
            __tagHelperExecutionContext = __tagHelperScopeManager.Begin("form", global::Microsoft.AspNetCore.Razor.TagHelpers.TagMode.StartTagAndEndTag, "06532c027761429406e6cb1c9a3599e1475dcd443671", async() => {
                WriteLiteral("\r\n    <div class=\"form-group\">\r\n        <label for=\"exampleFormControlInput1\">Nome</label>\r\n        <input type=\"email\" class=\"form-control\" id=\"exampleFormControlInput1\"");
                BeginWriteAttribute("placeholder", " placeholder=\"", 232, "\"", 246, 0);
                EndWriteAttribute();
                WriteLiteral(">\r\n    </div>\r\n    <div class=\"form-group\">\r\n        <label for=\"exampleFormControlInput1\">Descrição</label>\r\n        <input type=\"email\" class=\"form-control\" id=\"exampleFormControlInput1\"");
                BeginWriteAttribute("placeholder", " placeholder=\"", 435, "\"", 449, 0);
                EndWriteAttribute();
                WriteLiteral(">\r\n    </div>\r\n");
            }
            );
            __Microsoft_AspNetCore_Mvc_TagHelpers_FormTagHelper = CreateTagHelper<global::Microsoft.AspNetCore.Mvc.TagHelpers.FormTagHelper>();
            __tagHelperExecutionContext.Add(__Microsoft_AspNetCore_Mvc_TagHelpers_FormTagHelper);
            __Microsoft_AspNetCore_Mvc_TagHelpers_RenderAtEndOfFormTagHelper = CreateTagHelper<global::Microsoft.AspNetCore.Mvc.TagHelpers.RenderAtEndOfFormTagHelper>();
            __tagHelperExecutionContext.Add(__Microsoft_AspNetCore_Mvc_TagHelpers_RenderAtEndOfFormTagHelper);
            await __tagHelperRunner.RunAsync(__tagHelperExecutionContext);
            if (!__tagHelperExecutionContext.Output.IsContentModified)
            {
                await __tagHelperExecutionContext.SetOutputContentAsync();
            }
            Write(__tagHelperExecutionContext.Output);
            __tagHelperExecutionContext = __tagHelperScopeManager.End();
            WriteLiteral("\r\n<div class=\"form-group\">\r\n    <label for=\"exampleFormControlSelect1\">Categoria de Produtos</label>\r\n    <select class=\"form-control-sm\" id=\"exampleFormControlSelect1\">\r\n        ");
            __tagHelperExecutionContext = __tagHelperScopeManager.Begin("option", global::Microsoft.AspNetCore.Razor.TagHelpers.TagMode.StartTagAndEndTag, "06532c027761429406e6cb1c9a3599e1475dcd445828", async() => {
                WriteLiteral("Eletrônicos");
            }
            );
            __Microsoft_AspNetCore_Mvc_TagHelpers_OptionTagHelper = CreateTagHelper<global::Microsoft.AspNetCore.Mvc.TagHelpers.OptionTagHelper>();
            __tagHelperExecutionContext.Add(__Microsoft_AspNetCore_Mvc_TagHelpers_OptionTagHelper);
            await __tagHelperRunner.RunAsync(__tagHelperExecutionContext);
            if (!__tagHelperExecutionContext.Output.IsContentModified)
            {
                await __tagHelperExecutionContext.SetOutputContentAsync();
            }
            Write(__tagHelperExecutionContext.Output);
            __tagHelperExecutionContext = __tagHelperScopeManager.End();
            WriteLiteral("\r\n        ");
            __tagHelperExecutionContext = __tagHelperScopeManager.Begin("option", global::Microsoft.AspNetCore.Razor.TagHelpers.TagMode.StartTagAndEndTag, "06532c027761429406e6cb1c9a3599e1475dcd446799", async() => {
                WriteLiteral("Celulares");
            }
            );
            __Microsoft_AspNetCore_Mvc_TagHelpers_OptionTagHelper = CreateTagHelper<global::Microsoft.AspNetCore.Mvc.TagHelpers.OptionTagHelper>();
            __tagHelperExecutionContext.Add(__Microsoft_AspNetCore_Mvc_TagHelpers_OptionTagHelper);
            await __tagHelperRunner.RunAsync(__tagHelperExecutionContext);
            if (!__tagHelperExecutionContext.Output.IsContentModified)
            {
                await __tagHelperExecutionContext.SetOutputContentAsync();
            }
            Write(__tagHelperExecutionContext.Output);
            __tagHelperExecutionContext = __tagHelperScopeManager.End();
            WriteLiteral("\r\n        ");
            __tagHelperExecutionContext = __tagHelperScopeManager.Begin("option", global::Microsoft.AspNetCore.Razor.TagHelpers.TagMode.StartTagAndEndTag, "06532c027761429406e6cb1c9a3599e1475dcd447768", async() => {
                WriteLiteral("Informática");
            }
            );
            __Microsoft_AspNetCore_Mvc_TagHelpers_OptionTagHelper = CreateTagHelper<global::Microsoft.AspNetCore.Mvc.TagHelpers.OptionTagHelper>();
            __tagHelperExecutionContext.Add(__Microsoft_AspNetCore_Mvc_TagHelpers_OptionTagHelper);
            await __tagHelperRunner.RunAsync(__tagHelperExecutionContext);
            if (!__tagHelperExecutionContext.Output.IsContentModified)
            {
                await __tagHelperExecutionContext.SetOutputContentAsync();
            }
            Write(__tagHelperExecutionContext.Output);
            __tagHelperExecutionContext = __tagHelperScopeManager.End();
            WriteLiteral("\r\n    </select>\r\n</div>\r\n<td>\r\n    <div class=\"form-check\">\r\n        <input class=\"form-check-input\" type=\"checkbox\"");
            BeginWriteAttribute("value", " value=\"", 869, "\"", 877, 0);
            EndWriteAttribute();
            WriteLiteral(@" id=""defaultCheck1"">
        <label class=""form-check-label"" for=""defaultCheck1"">
            Perecível?
        </label>
    </div>
</td>
<p>
    <div class=""bnt-group"" role=""group"">
        <button type=""button"" class=""btn btn-primary"">Cadastrar</button>
    </div>

</p>
<div class=""text-center"">
    <table class=""table table-striped"">
        <thead>
            <tr>
                <th scope=""col"">Id</th>
                <th scope=""col"">Nome</th>
                <th scope=""col"">Descrição</th>
                <th scope=""col"">Categoria</th>
                <th scope=""col"">Ativo</th>
                <th scope=""col"">Ação</th>
                <td>
                    <div class=""bnt-group"" role=""group"">
                        <a role=""button""");
            BeginWriteAttribute("class", " class=\"", 1654, "\"", 1662, 0);
            EndWriteAttribute();
            WriteLiteral("></a>\r\n                        <a role=\"button\"");
            BeginWriteAttribute("class", " class=\"", 1710, "\"", 1718, 0);
            EndWriteAttribute();
            WriteLiteral(@"></a>
                    </div>
                </td>
            </tr>
        </thead>
        <tbody>
            <tr>
                <th scope=""row"">1</th>
                <td>Pen Drive</td>
                <td>Pen Drive 8 8gb</td>
                <td>Informática</td>
                <td>Ativo</td>
                <td>Não</td>
                <td>
                    <div class=""bnt-group"" role=""group"">
                        <a role=""button"" class=""btn btn-success"">Atualizar</a>
                        <a role=""button"" class=""btn btn-danger"">Deletar</a>
                    </div>
                </td>
            </tr>
            <tr>
                <th scope=""row"">2</th>
                <td>Iphone 5s</td>
                <td>Iphone 5s 16 gbytes - Apple</td>
                <td>Celulares</td>
                <td>Ativo</td>
                <td>Não</td>
                <td>
                    <div class=""bnt-group"" role=""group"">
                        <a role=""button"" cl");
            WriteLiteral(@"ass=""btn btn-success"">Atualizar</a>
                        <a role=""button"" class=""btn btn-danger"">Deletar</a>
                    </div>
                </td>
            </tr>
            <tr>
                <th scope=""row"">3</th>
                <td>Tv LG Smart</td>
                <td>Tv LG Smart 100 pol</td>
                <td>Eletrônicos</td>
                <td>Ativo</td>
                <td>Não</td>
                <td>
                    <div class=""bnt-group"" role=""group"">
                        <a role=""button"" class=""btn btn-success"">Atualizar</a>
                        <a role=""button"" class=""btn btn-danger"">Deletar</a>
                    </div>
                </td>
            </tr>
        </tbody>
    </table>
</div>

");
        }
        #pragma warning restore 1998
        #nullable restore
        [global::Microsoft.AspNetCore.Mvc.Razor.Internal.RazorInjectAttribute]
        public global::Microsoft.AspNetCore.Mvc.ViewFeatures.IModelExpressionProvider ModelExpressionProvider { get; private set; } = default!;
        #nullable disable
        #nullable restore
        [global::Microsoft.AspNetCore.Mvc.Razor.Internal.RazorInjectAttribute]
        public global::Microsoft.AspNetCore.Mvc.IUrlHelper Url { get; private set; } = default!;
        #nullable disable
        #nullable restore
        [global::Microsoft.AspNetCore.Mvc.Razor.Internal.RazorInjectAttribute]
        public global::Microsoft.AspNetCore.Mvc.IViewComponentHelper Component { get; private set; } = default!;
        #nullable disable
        #nullable restore
        [global::Microsoft.AspNetCore.Mvc.Razor.Internal.RazorInjectAttribute]
        public global::Microsoft.AspNetCore.Mvc.Rendering.IJsonHelper Json { get; private set; } = default!;
        #nullable disable
        #nullable restore
        [global::Microsoft.AspNetCore.Mvc.Razor.Internal.RazorInjectAttribute]
        public global::Microsoft.AspNetCore.Mvc.Rendering.IHtmlHelper<dynamic> Html { get; private set; } = default!;
        #nullable disable
    }
}
#pragma warning restore 1591
